[package]
name = "micro_6502"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.5.0"
clap = { version = "4.5.4", features = ["derive"] }
strum_macros = "0.25.2"
